<a href="https://colab.research.google.com/github/neerukondaramalakshmi2005-dotcom/Data-Analysis-/blob/main/EDA_PROJECT_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

In [12]:
data = pd.read_csv("/content/adult[1].csv")
print(data)

       Age          Workclass  Final Weight    Education  EducationNum  \
0       39          State-gov         77516    Bachelors            13
1       50   Self-emp-not-inc         83311    Bachelors            13
2       38            Private        215646      HS-grad             9
3       53            Private        234721         11th             7
4       28            Private        338409    Bachelors            13
...    ...                ...           ...          ...           ...
32556   27            Private        257302   Assoc-acdm            12
32557   40            Private        154374      HS-grad             9
32558   58            Private        151910      HS-grad             9
32559   22            Private        201490      HS-grad             9
32560   52       Self-emp-inc        287927      HS-grad             9

            Marital Status          Occupation    Relationship    Race  \
0            Never-married        Adm-clerical   Not-in-family   White
1       Married-civ-spouse     Exec-managerial         Husband   White
2                 Divorced   Handlers-cleaners   Not-in-family   White
3       Married-civ-spouse   Handlers-cleaners         Husband   Black
4       Married-civ-spouse      Prof-specialty            Wife   Black
...                    ...                 ...             ...     ...
32556   Married-civ-spouse        Tech-support            Wife   White
32557   Married-civ-spouse   Machine-op-inspct         Husband   White
32558              Widowed        Adm-clerical       Unmarried   White
32559        Never-married        Adm-clerical       Own-child   White
32560   Married-civ-spouse     Exec-managerial            Wife   White

        Gender  Capital Gain  capital loss  Hours per Week  Native Country  \
0         Male          2174             0              40   United-States
1         Male             0             0              13   United-States
2         Male             0             0              40   United-States
3         Male             0             0              40   United-States
4       Female             0             0              40            Cuba
...        ...           ...           ...             ...             ...
32556   Female             0             0              38   United-States
32557     Male             0             0              40   United-States
32558   Female             0             0              40   United-States
32559     Male             0             0              20   United-States
32560   Female         15024             0              40   United-States

       Income
0       <=50K
1       <=50K
2       <=50K
3       <=50K
4       <=50K
...       ...
32556   <=50K
32557    >50K
32558   <=50K
32559   <=50K
32560    >50K

[32561 rows x 15 columns]

| Function                  | Simple Definition                  |
| ------------------------- | ---------------------------------- |
| `data.info()`             | Gives complete dataset     information |
| `data.head()`             | Shows first 5 rows                 |
| `data.tail()`             | Shows last 5 rows                  |
| `data.describe()`         | Gives statistical summary          |
| `data.columns`            | Shows column names                 |
| `data.count()`            | Counts non-missing values          |
| `data.shape`              | Shows rows and columns             |
| `data.size`               | Shows total number of cells        |
| `data.isnull()`           | Finds missing values               |
| `data.isnull().sum()`     | Counts missing values              |
| `data.sum()`              | Calculates total                   |
| `data.min()`              | Finds minimum value                |
| `data.max()`              | Finds maximum value                |
| `data.duplicated()`       | Finds duplicate rows               |
| `data.duplicated().sum()` | Counts duplicate rows              |

In [ ]:

# UNDERSTANDING DATA SETS
# EDA is the process of understanding, cleaning, and exploring the dataset before building any model or dashboard.

data.head()
data.info()
data.describe()
data.tail()
data.columns
data.count()
data.shape
data.size
data.isnull().sum()
data.sum()
data.isnull()
data.min()
data.max()
data.duplicated()
data.duplicated().sum()

In [20]:

#data.info()--->	Gives complete dataset information
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             32561 non-null  int64
 1   Workclass       32561 non-null  object
 2   Final Weight    32561 non-null  int64
 3   Education       32561 non-null  object
 4   EducationNum    32561 non-null  int64
 5   Marital Status  32561 non-null  object
 6   Occupation      32561 non-null  object
 7   Relationship    32561 non-null  object
 8   Race            32561 non-null  object
 9   Gender          32561 non-null  object
 10  Capital Gain    32561 non-null  int64
 11  capital loss    32561 non-null  int64
 12  Hours per Week  32561 non-null  int64
 13  Native Country  32561 non-null  object
 14  Income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [19]:

#data.describe()	Gives statistical summary
data.describe()

,Age,Final Weight,EducationNum,Capital Gain,capital loss,Hours per Week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [17]:
# data.tail() --> it shows last 5 datasets
data.tail()

,Age,Workclass,Final Weight,Education,EducationNum,Marital Status,Occupation,Relationship,Race,Gender,Capital Gain,capital loss,Hours per Week,Native Country,Income
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [21]:
# data.head()---> it Shows first 5 rows
data.head()

,Age,Workclass,Final Weight,Education,EducationNum,Marital Status,Occupation,Relationship,Race,Gender,Capital Gain,capital loss,Hours per Week,Native Country,Income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [16]:

#data.shape--> it shows rows and columns
data.shape

(32561, 15)

In [41]:
#data.size-->	Shows total number of cells
data.size

488415

In [25]:

# data.columns -->Shows column names                 |
print(data.columns)

Index(['Age', 'Workclass', 'Final Weight', 'Education', 'EducationNum',
       'Marital Status', 'Occupation', 'Relationship', 'Race', 'Gender',
       'Capital Gain', 'capital loss', 'Hours per Week', 'Native Country',
       'Income'],
      dtype='object')

In [30]:

#  data.count()	--> Counts non-missing values
data.count()

Age               32561
Workclass         32561
Final Weight      32561
Education         32561
EducationNum      32561
Marital Status    32561
Occupation        32561
Relationship      32561
Race              32561
Gender            32561
Capital Gain      32561
capital loss      32561
Hours per Week    32561
Native Country    32561
Income            32561
dtype: int64

In [33]:
# data.isnull().sum()---> it is count missing values
data.isnull().sum()

Age               0
Workclass         0
Final Weight      0
Education         0
EducationNum      0
Marital Status    0
Occupation        0
Relationship      0
Race              0
Gender            0
Capital Gain      0
capital loss      0
Hours per Week    0
Native Country    0
Income            0
dtype: int64

In [34]:
#data.isnull()----> it is finding missing values
data.isnull()

,Age,Workclass,Final Weight,Education,EducationNum,Marital Status,Occupation,Relationship,Race,Gender,Capital Gain,capital loss,Hours per Week,Native Country,Income
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32557,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32558,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32559,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32560,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [35]:
#data.sum()---> it calculate all  total values
data.sum()

Age                                                         1256257
Workclass          State-gov Self-emp-not-inc Private Private Pr...
Final Weight                                             6179373392
Education          Bachelors Bachelors HS-grad 11th Bachelors Ma...
EducationNum                                                 328237
Marital Status     Never-married Married-civ-spouse Divorced Mar...
Occupation         Adm-clerical Exec-managerial Handlers-cleaner...
Relationship       Not-in-family Husband Not-in-family Husband W...
Race               White White White Black Black White Black Whi...
Gender             Male Male Male Male Female Female Female Male...
Capital Gain                                               35089324
capital loss                                                2842700
Hours per Week                                              1316684
Native Country     United-States United-States United-States Uni...
Income             <=50K <=50K <=50K <=50K <=50K <=50K <=50K >50...
dtype: object

In [36]:
#data.min() ---> it define the minimum value
data.min()

Age                                17
Workclass                           ?
Final Weight                    12285
Education                        10th
EducationNum                        1
Marital Status               Divorced
Occupation                          ?
Relationship                  Husband
Race               Amer-Indian-Eskimo
Gender                         Female
Capital Gain                        0
capital loss                        0
Hours per Week                      1
Native Country                      ?
Income                          <=50K
dtype: object

In [37]:
#data.max() ---> it define the maximum values
data.max()

Age                              90
Workclass               Without-pay
Final Weight                1484705
Education              Some-college
EducationNum                     16
Marital Status              Widowed
Occupation         Transport-moving
Relationship                   Wife
Race                          White
Gender                         Male
Capital Gain                  99999
capital loss                   4356
Hours per Week                   99
Native Country           Yugoslavia
Income                         >50K
dtype: object

In [39]:
#data.duplicated() ---> it find the duplicate rows
data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
32556    False
32557    False
32558    False
32559    False
32560    False
Length: 32561, dtype: bool

In [40]:

#data.duplicated().sum() ---> it count the duplicate removed_co_newlocals
data.duplicated().sum()

np.int64(24)

In [42]:
print(data)

       Age          Workclass  Final Weight    Education  EducationNum  \
0       39          State-gov         77516    Bachelors            13
1       50   Self-emp-not-inc         83311    Bachelors            13
2       38            Private        215646      HS-grad             9
3       53            Private        234721         11th             7
4       28            Private        338409    Bachelors            13
...    ...                ...           ...          ...           ...
32556   27            Private        257302   Assoc-acdm            12
32557   40            Private        154374      HS-grad             9
32558   58            Private        151910      HS-grad             9
32559   22            Private        201490      HS-grad             9
32560   52       Self-emp-inc        287927      HS-grad             9

            Marital Status          Occupation    Relationship    Race  \
0            Never-married        Adm-clerical   Not-in-family   White
1       Married-civ-spouse     Exec-managerial         Husband   White
2                 Divorced   Handlers-cleaners   Not-in-family   White
3       Married-civ-spouse   Handlers-cleaners         Husband   Black
4       Married-civ-spouse      Prof-specialty            Wife   Black
...                    ...                 ...             ...     ...
32556   Married-civ-spouse        Tech-support            Wife   White
32557   Married-civ-spouse   Machine-op-inspct         Husband   White
32558              Widowed        Adm-clerical       Unmarried   White
32559        Never-married        Adm-clerical       Own-child   White
32560   Married-civ-spouse     Exec-managerial            Wife   White

        Gender  Capital Gain  capital loss  Hours per Week  Native Country  \
0         Male          2174             0              40   United-States
1         Male             0             0              13   United-States
2         Male             0             0              40   United-States
3         Male             0             0              40   United-States
4       Female             0             0              40            Cuba
...        ...           ...           ...             ...             ...
32556   Female             0             0              38   United-States
32557     Male             0             0              40   United-States
32558   Female             0             0              40   United-States
32559     Male             0             0              20   United-States
32560   Female         15024             0              40   United-States

       Income
0       <=50K
1       <=50K
2       <=50K
3       <=50K
4       <=50K
...       ...
32556   <=50K
32557    >50K
32558   <=50K
32559   <=50K
32560    >50K

[32561 rows x 15 columns]